apiVersion: v1
kind: Service
metadata:
  name: kafdrop
spec:
  type: ClusterIP  # Or LoadBalancer if you need external access
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: kafdrop  # Must match your deployment's pod labels