apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafdrop-sa
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafdrop-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafdrop-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafdrop-role
subjects:
  - kind: ServiceAccount
    name: kafdrop-sa
    namespace: default